# environment-ci.yml (Place this in the ROOT of your repository)
name: saptase-ci
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.12 # Compatible with matrix versions
  - psi4>=1.9
  - pytest
  - pip             # Needed to run pip install below
  - numpy           # Add other dependencies needed for real tests
  - tqdm
  - dask
  - distributed
  - ruamel.yaml>=0.17,<0.19 # Needed for YAML config loading
  # - ruamel.yaml>=0.17,<0.19 # Add if needed by tests